version: "3.7"

services:

  org_api_server:
    build: .
    ports: 
      - 8080:8080
    depends_on:
      - db
    expose:
      - '8080'
    command: ["./wait-for-it.sh", "-t", "0", "db:3306", "--", "npm", "run", "start"]

  db:
    build: ./database
    command: --max_allowed_packet=32505856 
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: containerdb
      MYSQL_USER: devusr
      MYSQL_PASSWORD: devpw
    ports:
      - 3307:3306
    expose:
      - '3307'
